AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Inventory Exporter Lambda with scheduled trigger and S3 upload

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket where the CSV will be uploaded (must already exist)
  RegionName:
    Type: String
    Default: us-east-1
    Description: AWS Region for boto3 session in Lambda

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2InventoryLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EC2InventoryExportPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeVolumes
                  - ec2:DescribeTags
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub arn:aws:s3:::${S3BucketName}/EC2_Inventory/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - organizations:DescribeAccount
                  - sts:GetCallerIdentity
                Resource: "*"

  EC2InventoryLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ExportEC2Inventory
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: lambda_function_payload.lambda_handler
      Timeout: 300
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda-code/ec2_inventory_export.zip
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          REGION_NAME: !Ref RegionName

  ScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger Lambda daily at 8 AM UTC
      ScheduleExpression: cron(0 8 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt EC2InventoryLambda.Arn
          Id: LambdaTarget

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EC2InventoryLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduleRule.Arn
