AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to restrict EC2 instances to t3.micro when budget is exceeded (without BudgetAction)'

Parameters:
  BudgetLimit:
    Type: Number
    Default: 100
    Description: The budget limit amount in USD

  BudgetName:
    Type: String
    Default: 'MonthlyBudget'
    Description: Name of the budget

  EmailAddress:
    Type: String
    Description: Email address to receive budget notifications

  TargetIAMRole:
    Type: String
    Default: 'EC2UserRestrictedRole'
    Description: The IAM role to which the restrictive policy will be applied

Resources:
  BudgetActionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: budgets.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'BudgetActionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'iam:AttachRolePolicy'
                  - 'iam:DetachRolePolicy'
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${TargetIAMRole}'
              - Effect: 'Allow'
                Action:
                  - 'iam:AttachGroupPolicy'
                  - 'iam:AttachRolePolicy'
                  - 'iam:AttachUserPolicy'
                  - 'iam:CreatePolicy'
                  - 'iam:CreatePolicyVersion'
                  - 'iam:DeletePolicy'
                  - 'iam:DeletePolicyVersion'
                  - 'iam:DetachGroupPolicy' 
                  - 'iam:DetachRolePolicy'
                  - 'iam:DetachUserPolicy'
                  - 'iam:ListAttachedGroupPolicies'
                  - 'iam:ListAttachedRolePolicies'
                  - 'iam:ListAttachedUserPolicies'
                  - 'iam:ListPolicies'
                  - 'iam:ListPolicyVersions'
                  - 'iam:SetDefaultPolicyVersion'
                Resource: '*'
              - Effect: 'Allow'
                Action:
                  - 'ssm:GetParameters'
                  - 'ssm:GetParameter'
                Resource: '*'

  EC2RestrictPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 'Restricts EC2 instance creation to only t3.micro instances'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 'ec2:RunInstances'
            Resource: 'arn:aws:ec2:*:*:instance/*'
            Condition:
              StringEquals:
                'ec2:InstanceType': 't3.micro'
          - Effect: 'Allow'
            Action: 'ec2:RunInstances'
            Resource:
              - 'arn:aws:ec2:*:*:volume/*'
              - 'arn:aws:ec2:*:*:network-interface/*'
              - 'arn:aws:ec2:*:*:subnet/*'
              - 'arn:aws:ec2:*:*:security-group/*'
              - 'arn:aws:ec2:*:*:key-pair/*'
              - 'arn:aws:ec2:*::image/*'
          - Effect: 'Deny'
            Action: 'ec2:RunInstances'
            Resource: 'arn:aws:ec2:*:*:instance/*'
            Condition:
              StringNotEquals:
                'ec2:InstanceType': 't3.micro'
          - Effect: 'Allow'
            Action:
              - 'ec2:Describe*'
              - 'ec2:Get*'
            Resource: '*'

  MonthlyBudget:
    Type: 'AWS::Budgets::Budget'
    Properties:
      Budget:
        BudgetName: !Ref BudgetName
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: !Ref BudgetLimit
          Unit: USD
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref EmailAddress
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref EmailAddress

Outputs:
  BudgetName:
    Description: 'Name of the created budget'
    Value: !Ref BudgetName

  BudgetLimit:
    Description: 'Budget limit in USD'
    Value: !Ref BudgetLimit

  RestrictedPolicyArn:
    Description: 'ARN of the policy restricting EC2 instances'
    Value: !Ref EC2RestrictPolicy

  BudgetActionRoleArn:
    Description: 'ARN of the role used for budget actions'
    Value: !GetAtt BudgetActionRole.Arn
